FROM node:14.17.0-alpine3.13 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .


RUN npm run build --prod


FROM nginx:1.21.0-alpine


COPY --from=builder /app/dist/my-angular-app /usr/share/nginx/html


COPY nginx.conf /etc/nginx/nginx.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
