version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
 #     - npm install sonar-scanner --save-dev
      - npm i sonar-scanner --save-dev
      - npm run sonar-scanner
      - docker run  --rm  -e SONAR_HOST_URL="http://3.110.223.9:9000"  -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=test-project"  -e SONAR_TOKEN="sqp_972e763b1c0e03f1f976ce057a8a80c64df93bb8"  -v "./:/usr/src" sonarsource/sonar-scanner-cli
    #   - npx sonar-scanner
    #   - codebuild-breakpoint
    #   - ls
     # - docker run  --rm -v "$(pwd)":/usr/src/app -v sonarqube_cache:/root/.sonar/cache --network=host sonarsource/sonar-scanner-cli:latest -Dsonar.projectKey=angular-project -Dsonar.sources=. -Dsonar.host.url=http://13.232.66.119:9000 -Dsonar.token=sqp_56c3edda5bb4b36751f707f3d84b647d3c36e7a2

